In [8]:
import dhlab.module_update as mu
mu.update('dhlab_v2')
import dhlab_v2 as d2
import pandas as pd

Updated file `C:\Users\larsj\Documents\GitHub\Modules\dhlab_v2.py`

In [4]:
corpus = d2.document_corpus(doctype = 'digibok')

In [25]:
freqs = d2.frequencies(list(corpus.urn))

In [26]:
f = pd.DataFrame(freqs)

In [27]:
f

,URN:NBN:no-nb_digibok_2013071008027,URN:NBN:no-nb_digibok_2013101806052,URN:NBN:no-nb_digibok_2012072408038,URN:NBN:no-nb_digibok_2016052308143,URN:NBN:no-nb_digibok_2014121708203,URN:NBN:no-nb_digibok_2016100609088,URN:NBN:no-nb_digibok_2012012705005,URN:NBN:no-nb_digibok_2020071448643,URN:NBN:no-nb_digibok_2008040200099,URN:NBN:no-nb_digibok_2010082703006
$,1.0,5.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"0,78",1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0.,1.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,NaN
000.,1.0,NaN,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN
02,1.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
testosteronproduksjon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
trygghet,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
vekttap,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
spiser,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0
Transparent,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.0

In [24]:
words = f.sort_values(by = f.columns[0]).head(100000).index
len(words)

42235

In [23]:
%%time
d2.ngram_book(word = words, period = (1950, 1960)).transpose().sort_values(by = '1950', ascending = False)

Wall time: 1.96 s

,1950,1951,1952,1953,1954,1955,1956,1957,1958,1959,1960
â€”,1321193.0,772179.0,846710.0,801107.0,882687.0,796748.0,944091.0,1067140.0,1159507.0,1033445.0,1099948.0
I,371703.0,244444.0,259516.0,248395.0,388214.0,366149.0,370385.0,430477.0,404299.0,337686.0,439677.0
f,276138.0,160578.0,185593.0,167909.0,184606.0,165416.0,353586.0,379234.0,319518.0,234566.0,181497.0
',259059.0,180284.0,161680.0,192447.0,258434.0,245079.0,256745.0,267520.0,319079.0,270798.0,285222.0
Vi,115312.0,75889.0,79158.0,80121.0,83429.0,82941.0,78780.0,86242.0,97449.0,96006.0,120385.0
...,...,...,...,...,...,...,...,...,...,...,...
trade-off,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,NaN
trivially,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
vindicates,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
yif,NaN,1.0,1.0,NaN,NaN,9.0,NaN,1.0,6.0,NaN,1.0
Ã˜iolf,NaN,NaN,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN